type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  profilePictureUrl: String
}

type Game @table {
  title: String!
  releaseYear: Int!
  createdAt: Timestamp!
  genre: String
  developer: String
  publisher: String
  description: String
  coverImageUrl: String
}

type Platform @table {
  name: String!
  createdAt: Timestamp!
  manufacturer: String
}

type UserGame @table {
  user: User!
  game: Game!
  platform: Platform!
  ownedDate: Date!
  status: String!
  createdAt: Timestamp!
  personalRating: Int
  notes: String
}

type Follow @table(key: ["follower", "followed"]) {
  follower: User!
  followed: User!
  createdAt: Timestamp!
}